server:
  port: 7908
spring:
  application:
    name: aos-micoo-shopping-feign
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:aosco@localhost:8761/eureka,http://user:aosco@localhost:8762/eureka,http://user:aosco@localhost:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      Lindont: 123456  # 不会影响客户端行为
management:
  security:
    enabled: false
logging:
  level:
    com.aos.cloud.controller.UserFeignClient: DEBUG
# 打开Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true