spring:
  application:
    name: Eureka-Hight

security:
  basic:
    enabled: true
  user:
    name: user
    password: aosco

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://user:aosco@peer2:8762/eureka/,http://user:aosco@peer3:8763/eureka/

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:aosco@peer1:8761/eureka/,http://user:aosco@peer3:8763/eureka/

---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://user:aosco@peer1:8761/eureka/,http://user:aosco@peer2:8762/eureka/