server:
  port: 7902
spring:
  application:
    name: aos-micoo-web
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:aosco@peer1:8761/eureka,http://user:aosco@peer2:8762/eureka,http://user:aosco@peer3:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      Lindont: 123456  # 不会影响客户端行为
management:
  security:
    enabled: false
