server:
  port: 8760
security:
  basic:
    enabled: true
  user:
    name: user
    password: aosco
eureka:
  datacenter: cloud
  environment: product
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:aosco@localhost:8760/eureka

