server:
  port: 7901
spring:
  application:
    name: aos-micoo-movie
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:aosco@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      Lindont: 123456  # 不会影响客户端行为
management:
  security:
    enabled: false
aos-micoo-web:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule